### ISSUE TITLE
NX Ionic Angular - Not Compatible with latest NX?

### ISSUE THREAD

**Issue by SvenBudak** [nxext/nx-extensions-ionic#35]
I use node 22.2.0 and npm v 10.7.0

Steps to reproduce:

```console
$ npx create-nx-workspace@latest

√ Where would you like to create your workspace? · test-app
√ Which stack do you want to use? · none
√ Package-based monorepo, integrated monorepo, or standalone project? · integrated
√ Do you want Nx Cloud to make your CI fast? · skip
```

Then add angular:
```console
nx add @nx/angular
```

Then try to add ionic
```console
$ npm install --save-dev --exact @nxext/ionic-angular

npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: @anime-sector/source@0.0.0
npm error Found: @nx/angular@19.1.2
npm error node_modules/@nx/angular
npm error   dev @nx/angular@"^19.1.2" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @nx/angular@"18.2.4" from @nxext/ionic-angular@18.0.4
npm error node_modules/@nxext/ionic-angular
npm error   dev @nxext/ionic-angular@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error C:\Users\Sven\AppData\Local\npm-cache\_logs\2024-06-03T21_30_26_068Z-eresolve-report.txt
```

**Comment by PranavLR** [comment]
Try creating nx project with v18.2.4

`$ npx create-nx-workspace@18.2.4`

**Comment by DominikPieper** [comment]
@SvenBudak should work now with v19

**Comment by SvenBudak** [comment]
Hmmm now the error has changed, but still not working after i try to run `npm install --save-dev --exact @nxext/ionic-angular`

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@schematics/angular@18.0.4',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     npm: '^6.11.0 || ^7.5.6 || >=8.0.0',
npm WARN EBADENGINE     node: '^18.19.1 || ^20.11.1 || >=22.0.0',
npm WARN EBADENGINE     yarn: '>= 1.13.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v20.11.0', npm: '10.2.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/core@18.0.4',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     npm: '^6.11.0 || ^7.5.6 || >=8.0.0',
npm WARN EBADENGINE     node: '^18.19.1 || ^20.11.1 || >=22.0.0',
npm WARN EBADENGINE     yarn: '>= 1.13.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v20.11.0', npm: '10.2.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/schematics@18.0.4',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     npm: '^6.11.0 || ^7.5.6 || >=8.0.0',
npm WARN EBADENGINE     node: '^18.19.1 || ^20.11.1 || >=22.0.0',
npm WARN EBADENGINE     yarn: '>= 1.13.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v20.11.0', npm: '10.2.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/build-angular@18.0.4',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     npm: '^6.11.0 || ^7.5.6 || >=8.0.0',
npm WARN EBADENGINE     node: '^18.19.1 || ^20.11.1 || >=22.0.0',
npm WARN EBADENGINE     yarn: '>= 1.13.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v20.11.0', npm: '10.2.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular/compiler-cli@18.0.3',
npm WARN EBADENGINE   required: { node: '^18.19.1 || ^20.11.1 || >=22.0.0' },
npm WARN EBADENGINE   current: { node: 'v20.11.0', npm: '10.2.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular/compiler@18.0.3',
npm WARN EBADENGINE   required: { node: '^18.19.1 || ^20.11.1 || >=22.0.0' },
npm WARN EBADENGINE   current: { node: 'v20.11.0', npm: '10.2.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/architect@0.1800.4',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     npm: '^6.11.0 || ^7.5.6 || >=8.0.0',
npm WARN EBADENGINE     node: '^18.19.1 || ^20.11.1 || >=22.0.0',
npm WARN EBADENGINE     yarn: '>= 1.13.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v20.11.0', npm: '10.2.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/build-webpack@0.1800.4',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     npm: '^6.11.0 || ^7.5.6 || >=8.0.0',
npm WARN EBADENGINE     node: '^18.19.1 || ^20.11.1 || >=22.0.0',
npm WARN EBADENGINE     yarn: '>= 1.13.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v20.11.0', npm: '10.2.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular/build@18.0.4',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     npm: '^6.11.0 || ^7.5.6 || >=8.0.0',
npm WARN EBADENGINE     node: '^18.19.1 || ^20.11.1 || >=22.0.0',
npm WARN EBADENGINE     yarn: '>= 1.13.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v20.11.0', npm: '10.2.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@ngtools/webpack@18.0.4',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     npm: '^6.11.0 || ^7.5.6 || >=8.0.0',
npm WARN EBADENGINE     node: '^18.19.1 || ^20.11.1 || >=22.0.0',
npm WARN EBADENGINE     yarn: '>= 1.13.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v20.11.0', npm: '10.2.4' }
npm WARN EBADENGINE }
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Sven\\Desktop\\node_modules\\nx',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\Sven\Desktop\node_modules\nx'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Sven\\Desktop\\node_modules\\nx'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\Sven\\Desktop\\node_modules\\@nxext\\capacitor\\node_modules\\nx',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\Sven\Desktop\node_modules\@nxext\capacitor\node_modules\nx'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\Sven\\Desktop\\node_modules\\@nxext\\capacitor\\node_modules\\nx'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\Sven\Desktop\node_modules\@nx\workspace\node_modules\nx
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node ./bin/post-install
npm ERR! C:\Users\Sven\Desktop\node_modules\@nx\workspace\node_modules\nx\src\native\native-bindings.js:244
npm ERR!     throw loadError
npm ERR!     ^
npm ERR!
npm ERR! Error: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.
npm ERR! \\?\C:\Users\Sven\AppData\Local\Temp\nx-native-file-cache-20d3e0b\19.2.3-nx.win32-x64-msvc.node
npm ERR!     at Module._extensions..node (node:internal/modules/cjs/loader:1473:18)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1207:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:1023:12)
npm ERR!     at Module._load (C:\Users\Sven\Desktop\node_modules\@nx\workspace\node_modules\nx\src\native\index.js:60:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1235:19)
npm ERR!     at require (node:internal/modules/helpers:176:18)
npm ERR!     at Object.<anonymous> (C:\Users\Sven\Desktop\node_modules\@nx\workspace\node_modules\nx\src\native\native-bindings.js:66:29)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1376:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1207:32) {
npm ERR!   code: 'ERR_DLOPEN_FAILED'
npm ERR! }
npm ERR!
npm ERR! Node.js v20.11.0
```

**Comment by SvenBudak** [comment]
I tested it today again but still not working. are there any update for this topic? :)
